version: "3.3"
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./csv:/csv
    environment:
      LIMIT: 0    # Limit for scraped Games. 0 := not limit = all